services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: evdb
    volumes:
      - ../pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: tomas.silva@ipvc.pt
      PGADMIN_DEFAULT_PASSWORD: 123456789
    ports:
      - "8080:80"
    volumes:
      - ../pgadmin_data:/var/lib/pgadmin

  # se já vais carregar a BD pelo XML via script dentro do próprio server,
  # podes comentar/remover este serviço csv_loader.
  # csv_loader:
  #   image: python:3.10-slim
  #   depends_on:
  #     - db
  #   volumes:
  #     - ../../desafioaula2/data/ev_sales.csv:/workspace/ev_sales.csv:ro
  #     - ../import_csv_to_postgres.py:/workspace/import_csv_to_postgres.py:ro
  #   working_dir: /workspace
  #   environment:
  #     DB_HOST: db
  #     DB_PORT: "5432"
  #     DB_NAME: evdb
  #     DB_USER: postgres
  #     DB_PASSWORD: 123456789
  #     CSV_PATH: /workspace/ev_sales.csv
  #   command: bash -c "pip install psycopg2-binary pandas && python import_csv_to_postgres.py"

  grpc_server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: db_TP2B
      DB_USER: postgres   # corrigido: estava 'postgress'
      DB_PASSWORD: 123456789
    ports:
      - "50051:50051"
    volumes:
      # monta a pasta server/data local em /app/data dentro do container
      - ../data:/app/data

volumes:
  pgadmin_data:
